apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: trades-backend
    newName: trades-backend
    newTag: 74e55ea
  - name: trades-frontend
    newName: trades-frontend
    newTag: 74e55ea
