apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend
  namespace: trades-dashboard
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: trades-dashboard
      app.kubernetes.io/component: backend
